[package]
name = "sussy-malware"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.7", features = ["blocking"]}
bytes = "1.1.0"
filesize = "0.2.0"